### ISSUE TITLE
wordpress script

### ISSUE THREAD

**Issue by HarryF514** [sm0k3net/Useful-Scripts#1]
I got access denied after they asked me to enter a password for mysql. I left the password empty.

**Comment by sm0k3net** [comment]
Hi,

To configure all stuff properly were need to add all passwords, including database and phpmyadmin pass.

Check please this answer http://stackoverflow.com/questions/2101694/mysql-how-to-set-root-password-to-null

Best regards,
Uladzislau Murashka
