### ISSUE TITLE
Wordpress.sh

### ISSUE THREAD

**Issue by romprod** [sm0k3net/Useful-Scripts#2]
Hi, I'm using this on Ubuntu Server which now comes with PHP7.

Is it easy enough to change from Version 5 to Version7?

**Comment by sm0k3net** [comment]
Hi!
First of all, there may appear some issues with WordPress & PHP7:
https://make.wordpress.org/core/2015/09/10/wordpress-and-php7/
and https://premium.wpmudev.org/blog/updating-php-version/?utm_expid=3606929-97.J2zL7V7mQbSNQDPrXwvBgQ.0&utm_referrer=https%3A%2F%2Fwww.google.by%2F

If talk about this script and php7, actually I didn't watch for Ubuntu solutions, but have one for Debian when both php5 & php7 can be installed on server and work correctly.

```
$ cd /usr/local/src && wget https://www.dotdeb.org/dotdeb.gpg && apt-key add dotdeb.gpg
$ echo "deb http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list.d/dotdeb.list && \ echo "deb-src http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list.d/dotdeb.list
$ apt-get update
$ apt-get install php7.0 libapache2-mod-php7.0
$ apt-get install php7.0-mysql php7.0-curl php7.0-gd php7.0-intl php-pear php7.0-imagick php7.0-imap $ php7.0-mcrypt php7.0-pspell php7.0-recode php7.0-snmp php7.0-sqlite php7.0-tidy php7.0-xmlrpc $ php7.0-xsl
$ a2dismod php5 && a2enmod php7.0
$ service apache2 restart
```
